Programa ZZ_EXERCO01_##

REPORT ZZ_EXERCO01_00.

    DATA: 
      V_RUA TYPE STRING,
      V_MEDIA TYPE I, 
      V_CONTADOR TYPE I, 
      V_PRECO TYPE NETPR,
      V_AREA TYPE I,  
      V_OPCAO TYPE STRING,
      V_TELEFONE(11) TYPE C,  
